# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  
  schedule_order_locking:
    class: OrderLockingJob
    command: "OrderLockingJob.schedule_all_upcoming"
    schedule: every hour at minute 0
  
  lock_overdue_bake_days:
    class: OrderLockingJob
    command: "OrderLockingJob.lock_overdue_bake_days"
    schedule: every hour at minute 5

development:
  schedule_order_locking:
    class: OrderLockingJob
    command: "OrderLockingJob.schedule_all_upcoming"
    schedule: every hour at minute 0